export const DEFAULT_REDUCER_HELLO = 'DEFAULT_REDUCER_HELLO';
export const CHECKLOGIN_START = 'CHECKLOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_START = 'LOGIN_START';